name: CD Pipeline

on:
 push:
  branches: [ main ]
      

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: |
          docker build -t fastapi-app:latest .

      - name: "Tag Docker Images"
        run: |
         docker tag fastapi-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: "Push to Docker Hub"
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:latest

      - name: Deploy to server
        run: |
          sudo docker stop fastapi-app || true
          sudo docker rm fastapi-app || true
          sudo docker run -d --name fastapi-app -p 8000:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:latest
          EOF