name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:latest
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull the latest image
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:latest
            
            # Stop and remove existing container
            sudo docker stop fastapi-app || true
            sudo docker rm fastapi-app || true
            
            # Run new container
            sudo docker run -d \
              --name fastapi-app \
              -p 8000:8000 \
              --restart unless-stopped \
              -e PORT=8000 \
              -e HOST=0.0.0.0 \
              ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:latest \
              uvicorn app.main:app --host 0.0.0.0 --port 8000

              sudo docker ps -a | grep fastapi-app

              sudo docker logs fastapi-app

