name: CD pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker build -t $DOCKER_USERNAME/fastapi-app:latest .
        docker push $DOCKER_USERNAME/fastapi-app:latest
    
    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_key
        chmod 600 ssh_key
        mkdir -p ~/.ssh
        ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
        
        ssh -i ssh_key $SERVER_USER@$SERVER_HOST << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
          docker-compose down
          docker-compose up -d
        EOFname: CD Pipeline

on:
 push:
  branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker build -t fastapi-book-project:latest .

      - name: "Tag Docker Images"
        run: |
         docker tag fastapi-book-project:latest ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-book-project:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: "Push to Docker Hub"
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-book-project-app:latest

      - name: Add SSH private key
        run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa

      - name: Add SSH known hosts #
        run: |
         ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-book-project:latest
          sudo docker stop fastapi-book-project || true
          sudo docker rm fastapi-book-project || true
          sudo docker run -d --name fastapi-book-project -p 8000:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-book-project:latest
          EOF